// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "copy_conf.proto" (package "ec.copy", syntax proto2)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message ec.copy.CopyConf
 */
export interface CopyConf {
    /**
     * @generated from protobuf field: optional string pub_channel = 1;
     */
    pubChannel?: string;
    /**
     * @generated from protobuf field: optional string logpath = 2;
     */
    logpath?: string;
    /**
     * @generated from protobuf field: optional ec.copy.LogLevel loglevel = 3;
     */
    loglevel?: LogLevel;
    /**
     * @generated from protobuf field: optional uint32 width = 4;
     */
    width?: number;
    /**
     * @generated from protobuf field: optional uint32 height = 5;
     */
    height?: number;
    /**
     * @generated from protobuf field: optional string format = 6;
     */
    format?: string;
}
/**
 * @generated from protobuf enum ec.copy.LogLevel
 */
export enum LogLevel {
    /**
     * @generated from protobuf enum value: LOGLEVEL_START = 0;
     */
    LOGLEVEL_START = 0,
    /**
     * @generated from protobuf enum value: FETAL = 1;
     */
    FETAL = 1,
    /**
     * @generated from protobuf enum value: ERROR = 2;
     */
    ERROR = 2,
    /**
     * @generated from protobuf enum value: WARNING = 3;
     */
    WARNING = 3,
    /**
     * @generated from protobuf enum value: NOTICE = 4;
     */
    NOTICE = 4,
    /**
     * @generated from protobuf enum value: DEBUG = 5;
     */
    DEBUG = 5,
    /**
     * @generated from protobuf enum value: LOGLEVEL_END = 6;
     */
    LOGLEVEL_END = 6
}
// @generated message type with reflection information, may provide speed optimized methods
class CopyConf$Type extends MessageType<CopyConf> {
    constructor() {
        super("ec.copy.CopyConf", [
            { no: 1, name: "pub_channel", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "logpath", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "loglevel", kind: "enum", opt: true, T: () => ["ec.copy.LogLevel", LogLevel] },
            { no: 4, name: "width", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 5, name: "height", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 6, name: "format", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CopyConf>): CopyConf {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<CopyConf>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CopyConf): CopyConf {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string pub_channel */ 1:
                    message.pubChannel = reader.string();
                    break;
                case /* optional string logpath */ 2:
                    message.logpath = reader.string();
                    break;
                case /* optional ec.copy.LogLevel loglevel */ 3:
                    message.loglevel = reader.int32();
                    break;
                case /* optional uint32 width */ 4:
                    message.width = reader.uint32();
                    break;
                case /* optional uint32 height */ 5:
                    message.height = reader.uint32();
                    break;
                case /* optional string format */ 6:
                    message.format = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CopyConf, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string pub_channel = 1; */
        if (message.pubChannel !== undefined)
            writer.tag(1, WireType.LengthDelimited).string(message.pubChannel);
        /* optional string logpath = 2; */
        if (message.logpath !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.logpath);
        /* optional ec.copy.LogLevel loglevel = 3; */
        if (message.loglevel !== undefined)
            writer.tag(3, WireType.Varint).int32(message.loglevel);
        /* optional uint32 width = 4; */
        if (message.width !== undefined)
            writer.tag(4, WireType.Varint).uint32(message.width);
        /* optional uint32 height = 5; */
        if (message.height !== undefined)
            writer.tag(5, WireType.Varint).uint32(message.height);
        /* optional string format = 6; */
        if (message.format !== undefined)
            writer.tag(6, WireType.LengthDelimited).string(message.format);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ec.copy.CopyConf
 */
export const CopyConf = new CopyConf$Type();
