// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "radar_calib.proto" (package "ec.radar", syntax proto2)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message ec.radar.RadarCalibConfig
 */
export interface RadarCalibConfig {
    /**
     * @generated from protobuf field: optional double radar_orientation = 1;
     */
    radarOrientation?: number;
    /**
     * @generated from protobuf field: optional double radar_translation_x = 2;
     */
    radarTranslationX?: number;
    /**
     * @generated from protobuf field: optional double radar_translation_y = 3;
     */
    radarTranslationY?: number;
    /**
     * @generated from protobuf field: optional bool use_radar_extrinsic = 4;
     */
    useRadarExtrinsic?: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class RadarCalibConfig$Type extends MessageType<RadarCalibConfig> {
    constructor() {
        super("ec.radar.RadarCalibConfig", [
            { no: 1, name: "radar_orientation", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "radar_translation_x", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "radar_translation_y", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "use_radar_extrinsic", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<RadarCalibConfig>): RadarCalibConfig {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<RadarCalibConfig>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RadarCalibConfig): RadarCalibConfig {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional double radar_orientation */ 1:
                    message.radarOrientation = reader.double();
                    break;
                case /* optional double radar_translation_x */ 2:
                    message.radarTranslationX = reader.double();
                    break;
                case /* optional double radar_translation_y */ 3:
                    message.radarTranslationY = reader.double();
                    break;
                case /* optional bool use_radar_extrinsic */ 4:
                    message.useRadarExtrinsic = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RadarCalibConfig, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional double radar_orientation = 1; */
        if (message.radarOrientation !== undefined)
            writer.tag(1, WireType.Bit64).double(message.radarOrientation);
        /* optional double radar_translation_x = 2; */
        if (message.radarTranslationX !== undefined)
            writer.tag(2, WireType.Bit64).double(message.radarTranslationX);
        /* optional double radar_translation_y = 3; */
        if (message.radarTranslationY !== undefined)
            writer.tag(3, WireType.Bit64).double(message.radarTranslationY);
        /* optional bool use_radar_extrinsic = 4; */
        if (message.useRadarExtrinsic !== undefined)
            writer.tag(4, WireType.Varint).bool(message.useRadarExtrinsic);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ec.radar.RadarCalibConfig
 */
export const RadarCalibConfig = new RadarCalibConfig$Type();
