// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "recv_record_conf.proto" (package "ec.recvrecord", syntax proto2)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message ec.recvrecord.Conf
 */
export interface Conf {
    /**
     * @generated from protobuf field: optional string ec_img_channel = 1;
     */
    ecImgChannel?: string;
    /**
     * @generated from protobuf field: optional bool compress = 2;
     */
    compress?: boolean;
    /**
     * @generated from protobuf field: optional uint32 width = 3;
     */
    width?: number;
    /**
     * @generated from protobuf field: optional uint32 height = 4;
     */
    height?: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class Conf$Type extends MessageType<Conf> {
    constructor() {
        super("ec.recvrecord.Conf", [
            { no: 1, name: "ec_img_channel", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "compress", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "width", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 4, name: "height", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<Conf>): Conf {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Conf>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Conf): Conf {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string ec_img_channel */ 1:
                    message.ecImgChannel = reader.string();
                    break;
                case /* optional bool compress */ 2:
                    message.compress = reader.bool();
                    break;
                case /* optional uint32 width */ 3:
                    message.width = reader.uint32();
                    break;
                case /* optional uint32 height */ 4:
                    message.height = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Conf, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string ec_img_channel = 1; */
        if (message.ecImgChannel !== undefined)
            writer.tag(1, WireType.LengthDelimited).string(message.ecImgChannel);
        /* optional bool compress = 2; */
        if (message.compress !== undefined)
            writer.tag(2, WireType.Varint).bool(message.compress);
        /* optional uint32 width = 3; */
        if (message.width !== undefined)
            writer.tag(3, WireType.Varint).uint32(message.width);
        /* optional uint32 height = 4; */
        if (message.height !== undefined)
            writer.tag(4, WireType.Varint).uint32(message.height);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ec.recvrecord.Conf
 */
export const Conf = new Conf$Type();
