// @generated by protobuf-ts 2.8.1
// @generated from protobuf file "rsu.proto" (package "ec.rsu", syntax proto2)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message ec.rsu.Rsu
 */
export interface Rsu {
    /**
     * @generated from protobuf field: optional bool simu = 1;
     */
    simu?: boolean;
    /**
     * @generated from protobuf field: optional ec.rsu.Rsu.LogLevel loglevel = 2;
     */
    loglevel?: Rsu_LogLevel;
    /**
     * @generated from protobuf field: optional string logpath = 3;
     */
    logpath?: string;
    /**
     * @generated from protobuf field: int32 global_location_acquisition_mode = 4;
     */
    globalLocationAcquisitionMode: number;
    /**
     * @generated from protobuf field: optional string gnsssub_channel = 5;
     */
    gnsssubChannel?: string;
    /**
     * @generated from protobuf field: optional string rtk_conf = 6;
     */
    rtkConf?: string;
    /**
     * @generated from protobuf field: optional string app_name = 7;
     */
    appName?: string;
}
/**
 * @generated from protobuf enum ec.rsu.Rsu.LogLevel
 */
export enum Rsu_LogLevel {
    /**
     * @generated from protobuf enum value: LOGLEVEL_START = 0;
     */
    LOGLEVEL_START = 0,
    /**
     * @generated from protobuf enum value: FETAL = 1;
     */
    FETAL = 1,
    /**
     * @generated from protobuf enum value: ERROR = 2;
     */
    ERROR = 2,
    /**
     * @generated from protobuf enum value: WARNING = 3;
     */
    WARNING = 3,
    /**
     * @generated from protobuf enum value: NOTICE = 4;
     */
    NOTICE = 4,
    /**
     * @generated from protobuf enum value: DEBUG = 5;
     */
    DEBUG = 5,
    /**
     * @generated from protobuf enum value: LOGLEVEL_END = 6;
     */
    LOGLEVEL_END = 6
}
// @generated message type with reflection information, may provide speed optimized methods
class Rsu$Type extends MessageType<Rsu> {
    constructor() {
        super("ec.rsu.Rsu", [
            { no: 1, name: "simu", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "loglevel", kind: "enum", opt: true, T: () => ["ec.rsu.Rsu.LogLevel", Rsu_LogLevel] },
            { no: 3, name: "logpath", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "global_location_acquisition_mode", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "gnsssub_channel", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "rtk_conf", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "app_name", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Rsu>): Rsu {
        const message = { globalLocationAcquisitionMode: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Rsu>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Rsu): Rsu {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional bool simu */ 1:
                    message.simu = reader.bool();
                    break;
                case /* optional ec.rsu.Rsu.LogLevel loglevel */ 2:
                    message.loglevel = reader.int32();
                    break;
                case /* optional string logpath */ 3:
                    message.logpath = reader.string();
                    break;
                case /* int32 global_location_acquisition_mode */ 4:
                    message.globalLocationAcquisitionMode = reader.int32();
                    break;
                case /* optional string gnsssub_channel */ 5:
                    message.gnsssubChannel = reader.string();
                    break;
                case /* optional string rtk_conf */ 6:
                    message.rtkConf = reader.string();
                    break;
                case /* optional string app_name */ 7:
                    message.appName = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Rsu, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional bool simu = 1; */
        if (message.simu !== undefined)
            writer.tag(1, WireType.Varint).bool(message.simu);
        /* optional ec.rsu.Rsu.LogLevel loglevel = 2; */
        if (message.loglevel !== undefined)
            writer.tag(2, WireType.Varint).int32(message.loglevel);
        /* optional string logpath = 3; */
        if (message.logpath !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.logpath);
        /* int32 global_location_acquisition_mode = 4; */
        if (message.globalLocationAcquisitionMode !== 0)
            writer.tag(4, WireType.Varint).int32(message.globalLocationAcquisitionMode);
        /* optional string gnsssub_channel = 5; */
        if (message.gnsssubChannel !== undefined)
            writer.tag(5, WireType.LengthDelimited).string(message.gnsssubChannel);
        /* optional string rtk_conf = 6; */
        if (message.rtkConf !== undefined)
            writer.tag(6, WireType.LengthDelimited).string(message.rtkConf);
        /* optional string app_name = 7; */
        if (message.appName !== undefined)
            writer.tag(7, WireType.LengthDelimited).string(message.appName);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ec.rsu.Rsu
 */
export const Rsu = new Rsu$Type();
